# Generated by Django 5.0.4 on 2024-04-14 09:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=20, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MinValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(max_length=20, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('height', models.IntegerField(default=0, verbose_name='Height')),
            ],
            options={
                'verbose_name': 'Coord',
                'verbose_name_plural': 'Coords',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[(' ', ' '), ('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='Winter level', max_length=2)),
                ('summer', models.CharField(choices=[(' ', ' '), ('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='Spring level', max_length=2)),
                ('autumn', models.CharField(choices=[(' ', ' '), ('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='Summer level', max_length=2)),
                ('spring', models.CharField(choices=[(' ', ' '), ('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='Auturn level', max_length=2)),
            ],
            options={
                'verbose_name': 'Difficulty level',
                'verbose_name_plural': 'Difficulty levels',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=250, verbose_name='Family mame')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='^(\\+?\\d{1,3})?[-.\\s]?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$')], verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=200, verbose_name='Beauty title')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('other_titles', models.TextField(verbose_name='Other titles')),
                ('connect', models.TextField(blank=True, null=True, verbose_name='Connect')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Add time')),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'В ожидании'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=15, verbose_name='status')),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passage.coords', verbose_name='Coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passage.level', verbose_name='Level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passage.user', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pereval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='passage.pereval')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
