# Generated by Django 5.0.4 on 2024-04-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(choices=[('A1', 'Мery Easy'), ('A2', 'Easy'), ('B', 'Middle'), ('C1', 'Rough'), ('C2', 'Very Rough')], max_length=2, verbose_name='Summer level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(choices=[('A1', 'Мery Easy'), ('A2', 'Easy'), ('B', 'Middle'), ('C1', 'Rough'), ('C2', 'Very Rough')], max_length=2, verbose_name='Auturn level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(choices=[('A1', 'Мery Easy'), ('A2', 'Easy'), ('B', 'Middle'), ('C1', 'Rough'), ('C2', 'Very Rough')], max_length=2, verbose_name='Spring level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(choices=[('A1', 'Мery Easy'), ('A2', 'Easy'), ('B', 'Middle'), ('C1', 'Rough'), ('C2', 'Very Rough')], max_length=2, verbose_name='Winter level'),
        ),
    ]
