# Generated by Django 5.0.4 on 2024-04-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0002_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(choices=[('A1', 'Very Easy'), ('A2', 'Easy'), ('B', 'Middle'), ('C1', 'Rough'), ('C2', 'Very Rough')], default='Very easy', max_length=2, verbose_name='Summer level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(choices=[('A1', 'Very Easy'), ('A2', 'Easy'), ('B', 'Middle'), ('C1', 'Rough'), ('C2', 'Very Rough')], default='Very easy', max_length=2, verbose_name='Auturn level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(choices=[('A1', 'Very Easy'), ('A2', 'Easy'), ('B', 'Middle'), ('C1', 'Rough'), ('C2', 'Very Rough')], default='Very easy', max_length=2, verbose_name='Spring level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(choices=[('A1', 'Very Easy'), ('A2', 'Easy'), ('B', 'Middle'), ('C1', 'Rough'), ('C2', 'Very Rough')], default='Very easy', max_length=2, verbose_name='Winter level'),
        ),
    ]
