# Generated by Django 5.0.4 on 2024-04-14 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0003_alter_level_options_alter_level_autumn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=20, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(80)], verbose_name='Latitude')),
                ('longitude', models.FloatField(max_length=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('height', models.IntegerField(default=0, verbose_name='Height')),
            ],
            options={
                'verbose_name': 'Coord',
                'verbose_name_plural': 'Coords',
            },
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='coords',
        ),
        migrations.AddField(
            model_name='pereval',
            name='coord',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='passage.coord', verbose_name='Coord'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Coords',
        ),
    ]
