# Generated by Django 5.0.4 on 2024-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0005_alter_pereval_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='other_titles',
            field=models.TextField(blank=True, null=True, verbose_name='Other titles'),
        ),
    ]
