# Generated by Django 5.0.4 on 2024-04-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0007_remove_image_image_image_image_url_alter_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
