# Generated by Django 5.0.4 on 2024-04-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0008_remove_image_image_url_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('pending', 'если модератор взял в работу'), ('accepted', 'модерация прошла успешно;'), ('rejected', 'модерация прошла, информация не принята')], default='new', max_length=15, verbose_name='status'),
        ),
    ]
